# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 90, 250, 450))
        self.label.setStyleSheet("border-image:url(:/img/luis-gomes.jpg);\n"
"border-top-left-radius:20px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 90, 291, 451))
        self.label_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-bottom-right-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(420, 270, 201, 31))
        self.lineEdit.setStyleSheet("border:none;\n"
"background-color:rgb(255, 255, 255,0);\n"
"border-bottom:1px solid rgb(0, 0, 0);\n"
"color:rgb(0, 0, 0)")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(420, 340, 201, 31))
        self.lineEdit_2.setStyleSheet("border:none;\n"
"background-color:rgb(255, 255, 255,0);\n"
"border-bottom:1px solid rgb(0, 0, 0);\n"
"color:rgb(0, 0, 0)")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 400, 191, 51))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color:qlineargradient(spread:pad, x1:0.239, y1:0.295455, x2:1, y2:1, stop:0 rgba(198, 65, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-radius:15px;\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 460, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(186, 184, 180);")
        self.label_4.setObjectName("label_4")
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.label_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "欢迎登陆"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "输入账号"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "输入密码"))
        self.pushButton.setText(_translate("MainWindow", "登录"))
        self.label_4.setText(_translate("MainWindow", "忘记密码?"))
from resource import resource_rc
